name: sa7bi_ai
description: Sa7bi AI - Your smart Arabic AI companion.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # =========================
  # AUDIO
  # =========================
  audio_service: ^0.18.19
  just_audio: ^0.9.39
  audio_session: ^0.1.21

  # =========================
  # NETWORK / AI
  # =========================
  http: ^1.2.2

  # =========================
  # STORAGE
  # =========================
  shared_preferences: ^2.3.2

  # =========================
  # MEDIA
  # =========================
  image_picker: ^1.1.2
  file_picker: ^8.1.2

  # =========================
  # LINKS / SHARING
  # =========================
  url_launcher: ^6.3.1
  share_plus: ^10.0.2

  # =========================
  # PERMISSIONS
  # =========================
  permission_handler: ^11.3.1

  # =========================
  # UTILITIES
  # =========================
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - app_icon.png
